#Use the official Fedora Bootc base image
FROM quay.io/fedora/fedora-bootc:44

RUN dnf -y install \
    uboot-images-armv8 \
    bcm283x-firmware \
    bcm283x-overlays \
    && dnf clean all

# Install time synchronization and PTP packages
RUN dnf -y install \
    chrony \
    linuxptp \
    dnf5-plugins \
    && dnf clean all

# Commands for managing device with flightctl
#RUN dnf config-manager addrepo --from-repofile=https://rpm.flightctl.io/flightctl-epel.repo \
#    && dnf install -y flightctl-agent flightctl-cli\
#    && dnf clean all

# Enable services to run automatically at boot
RUN systemctl enable chronyd \
    && systemctl enable ptp4l \
    && systemctl enable flightctl-agent
